bower.json

Unfortunatly having `fin-*` in `devDependencies` creates a lot of 404 errors:

Moved dependencies

---

src/Hypergrid.js

@joneit 
It seems the assumption here was this would be triggered in response to an event and not directly from a  public api. 
Original code authoring PR
https://github.com/openfin/fin-hypergrid/commit/88fc53e37b31f8b3e78424016e094c6dbb965134#diff-d66e8d463b596a4633ae7cdafbf24db9R2955
Client said it was introduced in .15 but I see the issue as far back as 
http://openfin.github.io/fin-hypergrid/components/fin-hypergrid/examples/bclys/index.html

BUG/GRID-148: Removed potential exception

---

demo/js/demo.js
demo/js/widedata.js
src/Hypergrid.js
src/behaviors/Behavior.js
src/cellEditors/CellEditor.js
src/cellEditors/index.js
src/cellRenderers/CellRenderer.js
src/cellRenderers/index.js
src/dataModels/DataModel.js
src/jsdoc/interfaces.js
src/jsdoc/tutorials/cell-editors.md
src/jsdoc/tutorials/localization.md
src/lib/Localization.js

grid.registerCellEditor -> grid.cellEditors.add
grid.createCellEditor -> grid.cellEditors.create
Made `name` parameter optional for cellEditors.add, cellRenderers.add, localization.add
Added "hh:mm" example to demo.js
Added new column Birth Time to widedata.js
Expanded cell editors tutorial

CellEditors API is now an object that remembers grid ref

---

src/Hypergrid.js
src/behaviors/Behavior.js
src/behaviors/JSON.js
src/cellEditors/FilterBox.js
src/dataModels/JSON.js

dataModel/JSON.js:
- Now functions without aggregator or filter data sources.
- setData now re-uses previous data source if dataSource (1st param) is omitted.
- setData now passes 2nd param to constructor of first data source in the pipeline.
behaviors/Behavior.js, behaviors/JSON.js:
Changed calling signature for constructor (initialize method) from (grid, schema, dataRows) to (grid, dataRows, options).
Added options.fields, passed to dataMode/JSON.setData as 2nd param.

GRID-235: Externalize hyper-analytics (first step)

---

src/features/Feature.js

This was merely to suppress references to these on every feature doc page (due to @extends)

make prototype feature methods @private

---

demo/js/demo.js
package.json
src/cellEditors/CellEditor.js
src/dataModels/JSON.js
src/filter/DefaultFilter.js
src/filter/parser-CQL.js

Resolved by allowing operator synonyms even though not in menu proper.
Also added a property `opMustBeInMenu` to constrain typed-in op validity to menu.

GRID-308: Invalid operator

---

src/dialogs/ColumnPicker.js

Group view broke the Picker when no grouping methods are available (i.e., not mixed in). This fix _skips_ adding the grouping DnD lists when the methods are unavailable.
NOTE: This does not restore group picker effectiveness, which apparently has not worked since GRID-204 was merged.

Exclude grouping DnD lists from Picker when unavailable

---

README.md
add-ons/row-by-id.js
demo/example.html
demo/js/tree-view-separate-drill-down.js
demo/js/tree-view.js
package.json
src/dataModels/JSON.js
version-history.md

- Added release notes (version-history.html)
- Removed `getCell` from tree-view demos now that we have `halign` render property.
- Added missing semicolon to example.js

Version history 1.0.9

---

src/Hypergrid.js

Reverting... needs more research. turning off paint loop just means that repaints are done immediately and not periodically. not sure why turning it off reduced idle-time CPU usage, possibly simply because requestAnimationFrame was no longer running. in any case it only helped at idle time.

Revert "BUG/GRID-153"

---

demo/js/demo.js
src/Hypergrid.js
src/behaviors/Behavior.js
src/behaviors/Cell.js
src/behaviors/Column.js
src/dataModels/JSON.js
src/defaults.js
src/lib/Renderer.js
src/lib/deprecated.js
src/lib/json.js

Polishes off the way we build and handle the cell properties object, bringing it into line with the way the other properties objects work:
* The cell properties object is now `Object.create`'d from the column properties objects. This is in keeping with the way the column properties object is created from the grid properties object. Up to now, this cascade had to be done explicitly inline wherever it was needed.
* With this new paradigm, the renderer no longer needs to mix in the cell properties object as a final step after calling `getCell` but before calling the cell renderer's `paint` method. (However, added a new render property `reapplyCellProperties` to get the old behavior, where cell properties override `getCell` settings.)
* Cell properties objects no longer restricted to data …

cell props obj now created from column props obj

---

src/behaviors/Column.js
src/cellRenderers/SliderCell.js
src/cellRenderers/SparkBar.js
src/cellRenderers/SparkLine.js
src/cellRenderers/TreeCell.js
src/lib/Renderer.js

I removed the config object from the render instances since everywhere it is accessed (paint functions), it is being passed in as a parameter. Everything still seems to work. We can reinstate it if it turns out something obscure needed it.

remove config object from renderer instance

---

add-ons/tree-view.js
demo/js/demo.js
src/dataModels/JSON.js
src/dataSources/DataSourceOrigin.js

Paired PR with https://github.com/openfin/hyper-analytics/pull/30
To run this you would have to:
* use the hyper-analytics in https://github.com/openfin/hyper-analytics/pull/30
* uncomment the line you commented-out in behaviors/JSON.js:
```javascript
this.setGlobalFilter(this.getNewFilter());
```

GRID-364: Treeview: Do not filter parent rows

---

css/grid.css
src/cellEditors/CellEditor.js
src/cellEditors/ComboBox.js
src/cellRenderers/LastSelection.js
src/defaults.js

This addresses two issues:
* Cleans up cell editor so they look like they are more naturally a part of the grid. Essentially I removed the cell editor borders.
* Repositioned the drop down contents with a `left: 0` ... not sure why this broke.
Let's merge this and I'll push a branch `v1-1-1` of this commit for William's reference. I will also send him the patch file.
Tested in Chrome 53, Chrome 40, Firefox 48. Combobox always had problems in Safari. I just tried it in Safari 10.0 and still has issues. We should fix this at some point but I wouldn't hold up this merge for Safari.

GRID-403: Combobox dropdown contents positioning

---

css/grid.css
src/Hypergrid.js

Removed default container size/position styles from code and put in new css class `hypergrid-container`. There was a problem with instantiating multiple grids on the same page when depending on the container creation code. That code first looked for a container id="hypergrid" and if found, use it; if not found create it. So first time it created it; subsequently it found it, so kept appending additional grids inside it. I fixed this by
1. requring the found container to be empty in order to use it. 
2. Moved the naming to the initContainer function, but instead of always naming it hypergrid, I named it hypergrid, hypergrid1, hypergrid2, hypergrid3, etc.

container creation, naming, css class

---

add-ons/aggregations-view.js
add-ons/group-view.js
add-ons/tree-view.js
demo/js/demo.js
demo/js/tree-view-separate-drill-down.js
src/Hypergrid.js
src/behaviors/Behavior.js
src/behaviors/Column.js
src/behaviors/cellProperties.js
src/behaviors/columnProperties.js
src/cellEditors/FilterBox.js
src/dataModels/DataModel.js
src/dataModels/JSON.js
src/dialogs/ColumnPicker.js
src/features/CellEditing.js
src/features/CellSelection.js
src/features/ColumnMoving.js
src/features/ColumnPicker.js
src/features/ColumnSelection.js
src/features/RowSelection.js
src/features/ThumbwheelScrolling.js
src/lib/Renderer.js

move call to getDefaultState() to setState() and reset()
deprecate getPrivateState() in favor of grid.properties
change all refs to getPrivateState() to grid.properties
change all refs to tableState to grid.properties
deprecate resolveProperty(xxx) in favor of grid.properties[xxx]
change all refs to resolveProperty('xxx') to grid.properties.xxx
deprecate grid.getProperties in favor of .properties
change all grid.getProperties() to grid.properties
deprecated column.getProperties in favor of new column.properties getter
change all column.getProperties to column.properties
deprecated column.setProperties in favor of new column.properties setter AND column.addProperties

Moved behavior.tableState object to grid.properties

---

demo/performance.html
package.json
src/behaviors/Behavior.js
src/behaviors/Column.js
src/dataSources/DataSourceOrigin.js
src/lib/Renderer.js
src/lib/SelectionModel.js

@Dwaynekj One of the optimizations I put in 1.2.1 makes `getCell` changes to `config` look-and-feel props sticky till the bottom of each column. This was unintended. This patch restores it and I believe we should push this soon (like today). Unfortunately, we loose the ~1 FPS that was gained by this change.

v1.2.2 patch: getCell config should not be sticky

---

demo/js/demo.js
demo/performance.html
src/Hypergrid.js
src/cellRenderers/SimpleCell.js
src/lib/Renderer.js

Instead of doing this (v1.2.1):
* Set CSS backgroundColor style of canvas element to "line color."
* Draw a separate little rect for each cell.
We now do this (v1.2.2, proposed):
* Draw a single rect for the column.
* Draw a vertical line to left of each column rect.
* Draw a cell rect when and only when the background color of the cell differs from the column.
* After all columns are rendered, draw a horizontal line below each visible row.
Also retired feature where `config.backgroundColor`, `config.backgroundSelectionColor`, and `config.foregroundSelectionColor` can all be functions instead of strings. These are the only such properties that allow this. I suspect this feature preceded `getCell` because we never use it and it could also be done in`getCell`.

draw rect + v-lines per column + h-lines after

---

package.json
src/Hypergrid.js
src/lib/Canvas.js
src/lib/GraphicsContext.js
src/lib/gc-console-logger.js

Now uses grid.properties.doubleClickDelay, which if < 100ms turns off double click detection altogether.

Omit GraphicsContext object when no options.logger

---

add-ons/drill-down.js
add-ons/group-view.js
add-ons/totals-toolkit/mix-ins/behavior.js
css/grid.css
src/Base.js
src/Hypergrid.js
src/behaviors/Behavior.js
src/behaviors/JSON.js
src/behaviors/columnProperties.js
src/behaviors/index.js
src/behaviors/subgrids.js
src/dataModels/FilterSubgrid.js
src/dataModels/HeaderSubgrid.js
src/dataModels/JSON.js
src/dataModels/SummarySubgrid.js
src/dataModels/index.js
src/dialogs/Dialog.js
src/jsdoc/external-types.js
src/jsdoc/interfaces/dataModelAPI.js
src/jsdoc/interfaces/dataSourceHelperAPI.js
src/renderer/index.js

The subgrids option is now serializable. That is, you can now give strings instead of a references to data models. The strings are registered data model names (in src/dataModels/index.js).
Like grid renderers, these data model names are case-sensitive. This is however a break from our other name registries, such as cell renderers and cell editors. We clearly should be consistent, but rather than following suit, I'm thinking of making cell renderers and cell editors case-sensitive as well because its simpler, less code, more performant (cell renderers require a .toLowerCase() call on every cell on every render), and not too much to ask from developers who are after all already familiar with case-senstive identifers in Javascript. The only reason SWirts made them case insensitive was that …

GRID-373: Grid state, continued (part 2)

---

src/cellEditors/FilterBox.js

Fixes the issue simply by ignoring syntax errors in immediate mode (until editing stopped).

GRID-457: Prevent filter cell errors

---

add-ons/dialog-ui/index.js
add-ons/hyper-sorter/index.js
demo/js/demo.js
src/lib/events.js

`grid.reset()` calls `grid.removeAllEventListeners()`.
`grid.removeAllEventListeners()` goes through the list of added listeners and removes all that are not marked internal.
Unfortunately, I had forgotten to mark the internal event listeners as such so they were being removed. This PR fixes that: I added `true` as the (optional) second parameter to these `grid.addEventListener()` calls.
For the event listeners added by the demo (application level), I demonstrate another approach: Instead of marking them as internal, I re-add them after reset.
@Dwaynekj The internal event listeners I marked were all in events.js and were all listening for "fin-canvas" events, so this will of course conflict with your edits in your fin-canvas event PR...

GRID-484: Hypergrid reset regression - listeners

---

src/defaults.js
src/features/CellSelection.js

1. No longer checks to see if cell navigated away from had open editor
2. Now checks the prop on the cell navigated to rather than the cell navigated away from

GRID-483: Edit on keyboard navigation to any cell

---

src/Hypergrid.js
src/lib/SelectionModel.js

This additional PR for this ticket resets the selection model on hypergrid reset rather than recreating it, thus letting existing references remain valid.

GRID-484: Hypergrid reset regression

---

src/features/Filters.js

This additional PR for this ticket fixes keyboard navigation after having closed a filter cell with RETURN key. The problem was the line of code that selected the cell (the top visible cell of the column) was making the wrong "select" call.

GRID-471: Cell selection after filter cell

---

add-ons/aggregations-view.js
add-ons/group-view.js
demo/index.html
demo/js/demo.js
src/dataModels/JSON.js
src/dataModels/SummarySubgrid.js

@joneit 
We can hold off on merging this until alpha gets the ok (to avoid having to cherry pick late) *Please test locally*. You will also need this [PR](https://github.com/openfin/hyper-analytics/pull/47)
I need your help addressing these minor bugs (I'm a little tired)
* Unrelated bug in demo where clicking tree-view checkbox then clicking  "none" does not undo treeview
* Aggregations and Groupview Column have combobox editor on 
I can address this one
* Aggregations/GroupView leaves dirty state in the schema. As in the pink demo, if you do *onely* Agg/Grp on or off things work fine, but try toggling between Agg and Grp
I also got TravisCI running again

GRID-491: Aggregations And Group View Fix

---

src/behaviors/Column.js
src/behaviors/columnProperties.js
src/cellRenderers/SimpleCell.js
src/defaults.js

This makes it easy to delete or override the row handle `leftIcon` logic, or move it in its entirety to `centerIcon` or `rightIcon`, which answers the concern in the ticket.
See the updated [**_Icons_** wiki page](https://github.com/openfin/fin-hypergrid/wiki/Icons) for examples.

GRID-461: Icon functions

---

src/behaviors/columnProperties.js
src/cellRenderers/SimpleCell.js

Moves the filter icon logic to a getter on the properties object, similarly to Part 1 which moved the row handle icon code.
Both these enhancements merely make it easier to override that logic.

GRID-461: Icon functions, part 2

---

src/lib/dynamicProperties.js
src/renderer/index.js

Fix was simply to reset partial ('by-cells') grid renderer after any selection which forces it to use the fallback ('by-columns-and-rows') grid render for the next repaint.
Pushing without further approval because of time constraint. (We want to get it into alpha before Barc starts their day.)

GRID-490: Partial render leaves selection frame fragments

---

.gitignore
src/cellRenderers/SimpleCell.js
src/lib/Canvas.js

This lets app developer create and call synonyms for specific gc methods. Such methods may then be overridden (or not).

Canvas.graphicsContextAliases

---

demo/js/demo.js
src/features/ColumnResizing.js

Also fixes an error in console that occurs when 
Scenario A
1) Load Hypergrid Demo.
2) Click on Dashboard and click "Set Data 1(5000 rows)". To get more columns on the grid.
3) Scroll Horizontally so move to few columns to the right.
4) Now click on "FilterCell" and press Enter. 
5) You can see exception in console saying "columnIndex" not found.
Scenario B
1) Load Hypergrid Demo.
2) Apply a filter so that there are no records on the grid.
3) Now go back to the filter cell and press enter. 
4) You can see exception in console saying "rowIndex" not found.

Grid-459: Unable to resize Column

---

add-ons/aggregations-view.js
add-ons/group-view.js
add-ons/tree-view.js
package.json
src/Hypergrid.js
src/behaviors/Behavior.js
src/behaviors/Column.js
src/behaviors/cellProperties.js
src/behaviors/columnProperties.js
src/cellRenderers/TreeCell.js
src/dataModels/JSON.js
src/defaults.js
src/features/CellClick.js
src/features/ColumnResizing.js
src/lib/DataSourceOrigin.js
src/lib/cellEventFactory.js
src/renderer/bundle-columns.js
src/renderer/bundle-rows.js
src/renderer/by-cells.js
src/renderer/by-columns-and-rows.js
src/renderer/by-columns-discrete.js
src/renderer/by-columns.js
src/renderer/by-rows.js
src/renderer/index.js

@joneit 
Paired with https://github.com/openfin/hyper-analytics/pull/54
Resolves
https://github.com/openfin/fin-hypergrid/issues/535
https://github.com/openfin/fin-hypergrid/issues/501
https://github.com/openfin/fin-hypergrid/issues/488
https://github.com/openfin/fin-hypergrid/issues/483
https://github.com/openfin/fin-hypergrid/issues/563
Added Standard TreeColumn index -1, moving rowHandleColumn index to -2
Users can now build their own heirarchal view leveraging the treeColumn, and its open to customization as with other columns
Steps
`grid.properties.showTreeColumn = true`
Implement `grid.behavior.dataModel.isDrillDown()`
Implement `grid.behavior.dataModel.isDrillDownCol(y)`
Implement `grid.behavior.dataModel.isLeafNode(y)`
Overrid `grid.behavior.dataModel.toggleRow` // In the future …

ISSUE#563: Standard Tree Column

---

demo/js/demo/setState.js
src/Hypergrid.js
src/behaviors/Behavior.js
src/behaviors/subgrids.js
src/defaults.js
src/lib/dynamicProperties.js

See issue https://github.com/openfin/fin-hypergrid/issues/309 for details.
Task list:

ISSUE-309: Grid state, part 2

---

src/Hypergrid.js

@joneit I think this [issue](https://github.com/openfin/fin-hypergrid/issues/515) lies in how computeCellBounds builds the list of visibleColumns starting from the left where as the scrollH value diff is based on the right renderer.dataWindow.corner. The visibleColumns array maxes out based on available grid width before it even considering the column it was trying to show.

ISSUE-515: Cannot Scroll to last Column

---

src/Hypergrid.js

Without this, when instantiating a new grid and then adding theming properties with addProperties(),
the scroll limits are not updated and only a portion of the grid may be accessible on scroll.

Update scroll limits when adding new properties to the grid (defaultRowHeight may have changed)

---

src/Hypergrid.js
src/features/CellSelection.js
src/lib/cellEventFactory.js
src/lib/selection.js
src/renderer/index.js

This PR should fix multiple issues regarding the keyboard navigation.
1) Basic keyboard navigation wasn't working. 
2) Expanding selection with keyboard was broken when selection got bigger than viewport (either vertically or horizontally).
- Bug example with horizontal scrolling:
- Bug example with vertical scrolling:
3) Expanding selection vertically with keyboard was bugged when reaching the top of the grid

fix(#519): fix keyboard navigation

---

src/lib/cellEventFactory.js

This just hides the methods `getBasicColumnData` and `getBasicRowData` introduced in #598 by eliminating them entirely and making their code in-line.

remove "basic" method defs; make their code in-line

---

src/behaviors/Behavior.js
src/dataModels/JSON.js
src/lib/DataSourceOrigin.js
src/renderer/index.js

See issue #634 except this PR removes `treeColumnIndex` and `rowColumnIndex` from the data source entirely (without implementing an `options` object to hold them, as originally recommended in the issue).
Also addresses issue #641.

Remove treeColumnIndex/rowColumnIndex from DataSourceOrigin

---

src/lib/Canvas.js

When using hypergrid in a layout engine (like phosphor or golden-layout), sometimes these engines give the canvas a non-integral width and height, which causes text aliasing issues since canvas support subpixel referencing. This fix just floors the bounds of the canvas element in a consistent way.

Make sure canvas size is integral

---

src/Hypergrid.js
src/features/ColumnResizing.js
src/lib/modules.js
src/lib/scrolling.js

See Issue #660.
I tried moving the "changed"-related code to a separate file but it was only 60 lines so I undid it.
I did however move all scrolling-related members of `Hypergrid.prototype` to a separate file and then mixed it in.

Defer "xxxxChanged()" methods

---

src/lib/events.js
src/lib/selection.js

These props are costly to run so should not run unless actually needed.
Even though these were only invoked rarely (on specific user interactions), they could be _very_ costly if a lot of rows/columns are involved, in terms of memory and execution time.

Lazify event selection props

---

src/lib/Canvas.js

`mouseup` has to be on `document` to support column dragging — unlike other mouse events which are on `canvas`.
The problem was the handler for all grid instances receive `mouseup` events on a single mouse up.
This PR resolves this issue by implementing a "focused" `mouseup` handler, _i.e.,_ ignoring `mouseup` events except when preceded by the already-focused `mousedown` event. This works because only one of the grid instances could have gotten the `mousedown` (there being only one mouse pointer).

Focused mouseup

---

demo/index.html
package-lock.json
src/defaults.js
src/lib/dynamicProperties.js
src/renderer/index.js

More flexible alternative to _Draw a visual indication for fixed columns/rows when edge visible_ (#656) which had linter and other errors.
This version adjusts the grid render to _make room for_ the rule lines between the fixed and scrolling sections, which can now be of _any width_ (new grid property `fixedLineWidth`) — whereas the original version had no property, did not make room for the extra thick line, just _squeezing in_ an extra column (and/or row) of pixels (which is all there was room for).
As this new design allows us to have any width, I set the default to 3 rather than 2 which IMHO works better.
It also has an options for:
* Define `fixedEdgeWidth` for "double" rule line (of any scale) (defaults to `undefined`)
* Define `fixedLineColor` for specific color for this rule line …

flexible rule lines between fixed & scrolling rows & columns

---

src/lib/Canvas.js

Not sure why content editable was ever set on a canvas element, but in IE it causes the cursor to always be the I-beam shape. This fixes the first part of #617

FIx issue in IE with I-beam cursor

---

src/lib/events.js

If the grid has no data, this function starts throwing spurious console errors as the user mouses over the empty grid.

Don't do anything if there's no data

---

src/Hypergrid.js
src/defaults.js
src/lib/dynamicProperties.js
src/renderer/by-rows.js
src/renderer/index.js

**\[Supercedes #652, now closed without merge.]**
Although we had distinct properties, `gridLinesH` and `gridLinesV`, for enabling grid lines on the 2 axes, the other gridline properties, `lineColor` and `lineWidth`, pertained to both grid line axes simultaneously. **This PR creates distinct color and width properties.**
Implemented as a new _complex property_ (a property that is an object rather than a scalar), which gathers the 3 props (width, color, enabled) for each of 2 axes (vertical, horizontal) = 6 props all together into a single object [as defined in defaults.js](https://github.com/joneit/core/blob/935384d10c9874a874d51e30a700e17bba95a051/src/defaults.js#L449-L473)):
```js
. . .
gridLines: {
horizontal: {
enabled: true,
width: 1,
color: 'rgb(199, 199, 199)'
},
vertical: { …
```

Distinct vertical & horizontal line widths

---

demo/js/demo/index.js
demo/js/demo/setState.js
src/Hypergrid.js
src/behaviors/Behavior.js
src/behaviors/Column.js
src/behaviors/columnProperties.js
src/defaults.js
src/lib/dynamicProperties.js
src/renderer/by-rows.js
src/renderer/index.js

To hide one feature or the other, reset the new properties `rowHeaderFeatures.checkboxes` and `rowHeaderFeatures.numbers`. If both are reset, the entire column is hidden.
Setting the legacy property `showRowNumbers` still hides and shows the entire column by setting both of the above. Getting the legacy property returns `true` if either of the above are set.
> NOTE: First commit below, 0e7eff6, belongs to PR #674; please review that PR first; don't comment here on edits coming from that commit.

Hide row checkboxes & row numbers independently

---

demo/js/demo/celleditors.js
demo/js/demo/cellrenderers.js
src/Hypergrid.js
src/behaviors/Behavior.js
src/behaviors/JSON.js
src/behaviors/index.js
src/cellEditors/index.js
src/cellRenderers/index.js
src/defaults.js
src/features/Feature.js
src/features/index.js
src/lib/Registry.js
src/lib/dynamicProperties.js
src/lib/events.js

A property-based alternative to `behavior.features`.
Now the feature chain can be specified by `grid.properties.features` which is an array of registered feature names.
The advantage of making it a serializable property is that the feature chain can now be persisted along with other grid properties.
Caveat: Feature chain is delicate and dependent on the order of features. This approach is useful for omitting or substituting features, so long as the basic order is retained. Rearrange the order at your own risk!
Overriding `Behavior.prototype.features`, an array of feature constructors, is still supported and will get priority. (Override can take form of assigning to prototype before grid instantiation or  subclassing behavior with an override in subclass's prototype, and handing that …

Feature chain property

---

README.md
demo/index.html
demo/multiple-grids.html
demo/row-props.html
package-lock.json
package.json
src/behaviors/Behavior.js
src/behaviors/cellProperties.js
src/cellEditors/index.js
src/defaults.js
src/features/CellEditing.js
src/features/ColumnMoving.js
src/features/ColumnSorting.js
src/lib/Registry.js
src/lib/cellEventFactory.js
src/lib/events.js
src/renderer/index.js
src/renderer/layer-props.js

In testing v3 candidate, I've stumbled upon a couple of additional bugs in v2 upon which v3 is based (now rebased).
This release is in keeping with our plan is to continue to maintain v2 for those users who are not ready to upgrade to v3.
* `17611ae` - **regression:** fixed double-click logic to not throw error on unknown cell editor. So if `properties.editor` contains a string unknown to `grid.cellEditors.get()` (internally, the list is kept in `grid.cellEditors.items`), before this fix an error was thrown; after this fix, the cell is  simply uneditable.
* `b133b31` - **bug:** fixes a long-standing, pre-existing bug that was causing `removeAllEventListeners` to throw an error. The problem was trying to use `each` (which uses `forEach`) to delete a list's own members. Solution was to …

v2.1.3 - Two more bugs shaken out

---

src/Hypergrid.js
src/behaviors/Behavior.js
src/behaviors/subgrids.js
src/features/ColumnMoving.js
src/lib/events.js
src/renderer/index.js

Was suppressing events on empty data subgrid (scrollable portion) but should have been when _all_ subgrids were empty (no visible rows at all).
_Fix applied to v3 branch as well._

v2.1.5 - fixed issue suppressing events on empty grid

---

README.md
demo/index.html
demo/multiple-grids.html
demo/row-props.html
package-lock.json
package.json
src/Hypergrid.js
src/defaults.js
src/lib/Canvas.js
src/renderer/index.js

> NOTE: There will be no 2.1.9 release.
* Added new boolean grid props to more finely control where grid lines are rendered (all `true` by default):
* `gridLinesColumnHeader`
* `gridLinesRowHeader`
* `gridLinesUserDataArea`
* Respect new `top` property of `grid.renderer.visibleColumns` elements _when defined._ (Set by grouped-headers plug-in to adjust lines so they're not drawn over group labels).
* Respect new `bottom` property of `grid.renderer.visibleColumns` elements _when defined_ (Set by grouped-headers plug-in to prevent lines from being drawn between column headers). When `bottom` is in the header _and_ `gridLinesUserDataArea` is truthy,  another line is drawn for the user data area.
* When the paint loop is not running (rarely used debug feature; not issues when paint loop is …

Hypergrid v2.1.9

---

README.md
demo/formatter-workbench/instructions.html
demo/index.html
demo/js/demo/index.js
demo/multiple-grids.html
demo/row-props.html
package-lock.json
package.json
src/Hypergrid.js
src/features/ColumnMoving.js
src/lib/Canvas.js
src/renderer/by-cells.js
src/renderer/by-columns.js

1. Fix partial render grid lines (Issue #730)
2. Option to turn off canvas's alpha channel
3. Fix error in `Hypgrid.prototype.terminate`
4. Add more dashboard controls to `demo/row-props.html`
5. Add `autosizeGroups` and documentation to `fin-hypergrid-grouped-header-plugin`
This issue affects the "partial renderer" only. The partial render is the "by-cells" grid renderer, which is the "difference engine" renderer that only repaints cells whose contents has changed. This renderer has the major advantage of speed, up to 5x faster (!).
The issue was that the cells were overwriting the lines previously drawn by the key frame render. This is because in the default "boxSizing" mode (`grid.properties.boxSizing = 'border-box'`), cell contents _includes_ the one-pixel borders.
The fix was to …

Hypergrid v2.1.15

---

README.md
package.json
src/Hypergrid/index.js
src/Hypergrid/modules.js
src/behaviors/Column.js
src/defaults.js
src/features/ColumnResizing.js
src/lib/Canvas.js
src/lib/SelectionModel.js
src/renderer/index.js

This is a "minor version update" which is interface-backwards-compatible with v3.0.* but introduces a new feature, the `maximumColumnWidth` prop _(see below)._
> NOTE: Although the merge branch is called `v3.0.4` the version has been bumped to `3.1.0`.
This release also contains:
* Bug fixes
* Simplified license
* Improved tutorial (still a WIP though)
1. Fix bug in `getSelectedRows` 
2. `renderLastSelection` now bails on missing rows
3. Update keys down array when shift key changes
4. Update keys down array whenever referenced by mouse event handlers
5. Implement `maximumColumnWidth` prop
6. Capture off-grid `mouseup` during scrollbar thumb drag
7. Retain scrollbar thumb's `.hover` CSS class throughout drag
8. Normalize mouse wheel metrics across platforms and browsers
9. Better dates in …

Hypergrid v3.1.0

---

src/Base.js

This PR targets the next release, `v3.2.0`.
```js
Base.prototype.versionAtLeast = function(version /* string */) { ... return /*boolean*/ }
```
This new function compares the passed version string to the current version and returns `true` if the current version is newer. Caveat: Because it's new, it is only useful for arguments >= `3.2.0`.

Add Base.prototype.versionAtLeast

---

src/lib/Registry.js

This PR targets the next release, `v3.2.0`.
```js
Registry.prototype.make = function(name, prototype) // name is optional
```
This new convenience method creates a new class extended from the registry's base class (registry.BaseClass) and then adds it. The registry name is determined either by the first parameter if provided OR from a `name` property or `$$CLASS_NAME` property in the provided prototype.

Add Registry.prototype.make

---

src/behaviors/Column.js

This PR (specifically 1727b44) fixes the bug reported in Issue #784.
This issue was with the `column.calculator` property overload where the value is a stringified anonymous function (use case 2 below).
The `calculator` property setter is overloaded for any of the following use cases:
1. Registered function name
* Function is dereferenced from the calculators registry
2. _Anonymous_ stringified function
* The string is functionified (inflated into an actual function object)
* The function is registered (if not already in the registry) using the _entire function string_ as the registry key
* Registering the function normalizes other references to it, _i.e.,_ other references to the identical function string will not be individually functionified but will use the function in the registry
3. …

Issue #784 Anonymous column calculator bug

---

src/defaults.js
src/lib/Canvas.js

This dubious feature which was off by default did not contribute anything to performance (on Chrome at least) and complicated the code.
Removed `grid.properties.useBitBlit`, `grid.canvas.bc`, `grid.canvas.buffer`; the `grid.canvas.flushBuffer()` method is now a no-op.
Not sure why the original author thought this would help. Normally used to composite smaller bitmpas into a larger bitmap so those portions don't have to redraw the entire view on every frame. This is not the case with Hypergrid where we are redrawing the entire grid on every frame. The other concept of prepping an off-stage view while the user is looking at the current frame is not an advantage if the entire frame can be drawn during blanking. There is no parallel processing in JS especially when GPU is bottleneck. Maybe I …

removed blitting support

---

src/Hypergrid/index.js
src/cellEditors/CellEditor.js
src/defaults.js
src/features/ColumnMoving.js
src/lib/Canvas.js

HTMLElement..style.zoom is non-standard but widely supported. (The only exception is Firefox.)
This PR adds the following support for when a Hypergrid is zoomed by this feature (when any elements from `<body>` to `<canvas>` have their `zoom` style set to something other than `1`):
1. Canvas resolution is now optimized with respect to the zoom settings of all the elements in the chain
2. Mouse tracking coordinates are now properly adjusted when zoomed
Tested on Chrome, Safari, IE 11 (which needed some special case coding), and regression tested on Firefox where it has no effect.
Added method `grid.resetZoom()` which should be called:
1.  **Any time you set the `zoom` style of one or more of the elements in the chain.** This does two things: Optimizes the canvas resolution; adjusts the …

Respect style.zoom

---

src/Hypergrid/index.js
src/features/ColumnMoving.js
src/lib/Canvas.js

[`style.zoom`](https://developer.mozilla.org/en-US/docs/Web/CSS/zoom) is non-standard but widely supported. (The only exception is Firefox.)
This PR adds the following support for when a Hypergrid is zoomed by setting `document.body.style.zoom`:
1. Canvas resolution is now optimized with respect to the zoom settings of all the elements in the chain
2. Mouse tracking coordinates are now properly adjusted when zoomed
Tested on Chrome, Safari, IE 11, and regression tested on Firefox where it has no effect.
Added method `grid.resetZoom()` which should be called:
1.  **Any time you set the `document.body.style.zoom`.** This does two things: Optimizes the canvas resolution; adjusts the mouse coordinates.
2.  **After user adjusts browser zoom using ctrl +/- to optimize the resolution.** This …

respect document.body.style.zoom
