index.html
src/Hypergrid.js
src/Renderer.js
src/behaviors/Behavior.js
src/behaviors/Column.js
src/behaviors/DataModelDecorator.js
src/dataModels/DecoratorBase.js
src/dataModels/JSON.js

several bug fixes

---

src/Hypergrid.js

Bug/Grid-136 Fix for copy selection

---

src/Hypergrid.js
src/features/CellSelection.js

BUG/GRID-146 Changes for scrolling with D-pad

---

src/Shared.js
src/behaviors/Column.js
src/defaults.js
src/lib/Renderer.js

no data to display message added

---

src/defaults.js
src/lib/Renderer.js

feature/GRID-156 Added property to configure vertical grid line lenght

---

src/Hypergrid.js
src/behaviors/JSON.js
src/dialogs/ColumnPicker.js

@joneit 
Test in 
```
Object.keys(g.getRowSelection()).length
Object.keys(g.getRowSelection(true)).length
```

feature/GRID-183: Draft of getSelectionRows with hidden rows for in-memory data

---

demo/js/demo.js
src/behaviors/Column.js
src/behaviors/JSON.js
src/dataModels/JSON.js
src/defaults.js
src/dialogs/ColumnPicker.js

WIP: BUG/Grid-155

---

demo/js/demo.js
src/behaviors/JSON.js
src/dialogs/ColumnPicker.js

BUG/GRID-155 Cleanup-Removed unnecessary repaint

---

demo/js/demo.js

BUG/GRID-246 Minor bug fix

---

src/cellRenderers/LastSelection.js

IMPR/GRID-233: Turned off Selection Marquee

---

src/jsdoc/tutorials/cell-renderer.md

IMPRV/GRID-233: Docs updates

---

src/Hypergrid.js
src/lib/SelectionModel.js

BUG/GRID-208: Fixed double selection changed event

---

src/lib/SelectionModel.js

TASK/GRID-240 Added firstSelectedCell

---

README.md

@Dwaynekj @joneit I reordered some of the sections and updated some of the formatting. Hope this is okay!

Update formatting and section order

---

demo/js/demo.js
src/cellEditors/CellEditor.js
src/cellEditors/FilterBox.js
src/filter/parser-CQL.js

Sill needs expression tokenization

GRID-267: Replace operator in filter cell

---

package.json
src/Shared.js

Reverts openfin/fin-hypergrid#216

Revert "bumped hyper-analytics version; adjusted shared to npm"

---

package.json
src/Shared.js

Reverts openfin/fin-hypergrid#217

Bump hyper-analytics version reference; point to npm

---

demo/calculated-column.html
demo/js/calculated-column.js
package.json

@Dwaynekj See the [fincanvas PR](https://github.com/openfin/fincanvas/pull/1).

GRID-272: Clear grid completely on zoom

---

README.md

@joneit @Dwaynekj Per our [Google Sheets draft](https://docs.google.com/spreadsheets/d/1fc7sjIwM_Xkfz9jxhjhUlFLy017jcEV1f7v7a6Kjve0/edit#gid=0), we'd like to expand on the **Features** section in our Readme. Feel free to merge and push out with the next release. Thanks.

Update Features section

---

demo/example.html
package.json
src/Hypergrid.js
src/behaviors/Behavior.js
src/behaviors/JSON.js
src/dataModels/JSON.js

Reverts openfin/fin-hypergrid#267 @joneit Let's review this first please

Revert "Arctic Lake: Add addDataRow, modify, delete, update, fetch methods"

---

demo/example.html
package.json
src/Hypergrid.js
src/behaviors/Behavior.js
src/behaviors/JSON.js
src/dataModels/JSON.js

Reverts openfin/fin-hypergrid#268

Revert "Revert "Arctic Lake: Add addDataRow, modify, delete, update, fetch methods""

---

.travis.yml
README.md

@Dwaynekj @joneit now on develop.

added travis ci integration.

---

src/defaults.js

IMPRV/Fixed docs for defaults.js

---

src/Hypergrid.js

fixed context menu propagation

---

gulpfile.js
package.json
test/Base-test.js
test/SelectionModel-tests.js
test/css-test.js
test/html-test.js
test/image-test.js

@joneit @Dwaynekj check it out, nothing super involved but a basic harness. 
Will be back for some selection model tests.

added first set of unit tests

---

test/SelectionModel-tests.js

@Dwaynekj Feel free to merge this. I have to get on the road soon. C u later at JPM.

augmented grid mock for SelectionModel test

---

demo/js/group-view.js
src/Hypergrid.js
src/lib/Renderer.js

@Dwaynekj Vertical scroll bar now positioned correctly on right edge of canvas, as in for example group-view.html.

GRID-307: Remove 200px kludge

---

version-history.md

Added more versions notes

---

src/dialogs/ColumnPicker.js

BUG/GRID-328 Was calling setGroups one layer too deep

---

demo/js/tree-view-separate-drill-down.js
package.json

This basically just bumps the hyper-analytics version to 0.11.16.
Also fixes a bug in the "separate drill down column" treeview demo.

GRID-365: Treeview Sorting Fix

---

add-ons/aggregations-view.js
add-ons/drill-down.js
add-ons/group-view.js
add-ons/grouped-header.js
add-ons/hyper-filter/index.js
add-ons/hyper-sorter/index.js
add-ons/row-by-id.js
add-ons/tree-view.js
demo/calculated-column.html
demo/js/aggregations-view.js
demo/js/calculated-column.js
demo/js/demo.js
demo/js/group-view.js
demo/js/grouped-header.js
demo/js/tree-view-separate-drill-down.js
demo/js/tree-view.js
src/Hypergrid.js

Got inspired on the train. Hope y'all like it.

GRID-384: Plugins

---

src/dataModels/JSON.js

Sent diff to customer via email last night at 7:55 PM EDT.

GRID-388: Expand/Collapse behavior

---

demo/js/demo.js
src/Hypergrid.js
src/behaviors/JSON.js

@joneit @rdepena 
setData doesn't cause the grid to jitter on an update! Great for remote

IMPR/GRID-392 (resetData)

---

add-ons/hyper-sorter/mix-ins/dataModel.js
demo/js/demo.js
src/dataSources/DataSourceOrigin.js

Dependent on merging https://github.com/openfin/fin-hypergrid/pull/367

IMPRV/DataSourceOrigin:FindRowByIndex

---

src/Hypergrid.js
src/lib/events.js
src/lib/selection.js

These new files are mixed into Hypergrid.js.

Added lib/events.js and lib/selection.js

---

package.json
src/defaults.js

**Requires GRID-414 (https://github.com/openfin/fin-hypergrid/pull/384) to be merged first before running.**

GRID-415: Measure text by individual characters

---

src/behaviors/Behavior.js
src/defaults.js
src/lib/Renderer.js

See the [GRID-417](https://appoji.jira.com/browse/GRID-417) Jira ticket for details.

GRID-417: Row number column width

---

src/cellRenderers/SimpleCell.js

See the [GRID-418](https://appoji.jira.com/browse/GRID-418) Jira ticket for details.

GRID-418: Avoid unnecessary text measuring

---

demo/performance.html
src/cellRenderers/CellRenderer.js
src/cellRenderers/ErrorCell.js
src/cellRenderers/SimpleCell.js
src/defaults.js

See the [GRID-419](https://appoji.jira.com/browse/GRID-419) Jira ticket for details.

GRID-419: Truncate text as needed

---

src/cellRenderers/Button.js
src/cellRenderers/SimpleCell.js
src/cellRenderers/TreeCell.js
src/defaults.js
src/features/ColumnResizing.js
src/lib/Canvas.js
src/lib/Renderer.js
src/lib/graphics.js

See [GRID-421](https://appoji.jira.com/browse/GRID-421) Jira ticket for details.

GRID-421: Right-side icon bad background

---

demo/js/demo.js
src/behaviors/Behavior.js
src/behaviors/JSON.js
src/cellEditors/CellEditor.js
src/lib/Renderer.js
src/lib/cellEventFactory.js
src/lib/events.js

See Jira [GRID-422](https://appoji.jira.com/browse/GRID-422) for details.

GRID-422: Add `row` prop (getter) to CellEvent

---

src/behaviors/JSON.js
src/dataModels/FilterSubgrid.js
src/dataModels/HeaderSubgrid.js
src/dataModels/SummarySubgrid.js

See Jira [GRID-423](https://appoji.jira.com/browse/GRID-423) for details.

GRID-423: Fix header getRow

---

add-ons/grouped-header.js
src/Base.js
src/Hypergrid.js
src/behaviors/Behavior.js
src/behaviors/Column.js
src/behaviors/columnProperties.js
src/cellRenderers/SimpleCell.js
src/dataModels/HeaderSubgrid.js
src/dataModels/SummarySubgrid.js
src/defaults.js
src/lib/Localization.js
src/lib/Renderer.js
src/lib/cellEventFactory.js

See Jira [GRID-424](https://appoji.jira.com/browse/GRID-424) for details.
This PR will have an expected merge conflict with https://github.com/openfin/fin-hypergrid/pull/394 in HeaderSubgrid.js.

GRID-424: Remove presentation logic from header data model

---

src/behaviors/columnProperties.js
src/dataModels/SummarySubgrid.js
src/defaults.js
src/lib/Renderer.js
src/lib/cellEventFactory.js
src/lib/toFunction.js

Also fixed column background color and summary row getValue.

GRID-428: Remove unneeded props and props objs

---

demo/row-props.html

See Jira [GIRD-444](https://appoji.jira.com/browse/GRID-444) for details.

GRID-444: Demo row and column bundling

---

demo/row-props.html
src/Hypergrid.js
src/behaviors/JSON.js
src/dataModels/FilterSubgrid.js
src/dataModels/HeaderSubgrid.js
src/lib/Canvas.js
src/renderer/by-cells.js
src/renderer/by-columns-and-rows.js
src/renderer/by-columns-discrete.js
src/renderer/by-columns.js
src/renderer/by-rows.js
src/renderer/index.js

@Dwaynekj This PR cleans up some issues with the earlier one and resolves some edge cases. I'm going to go ahead and merge it.

GRID-438: "No data message" mop-up

---

demo/js/demo.js
src/Hypergrid.js
src/cellEditors/CellEditor.js
src/cellEditors/FilterBox.js
src/defaults.js
src/lib/selection.js
src/renderer/index.js

See Jira [GRID-431](https://appoji.jira.com/browse/GRID-431) for details.

GRID-431: Misaligned filter cell editor

---

add-ons/grouped-header.js
add-ons/totals-toolkit/mix-ins/behavior.js
demo/js/demo.js
src/Hypergrid.js
src/behaviors/Behavior.js
src/behaviors/Column.js
src/behaviors/JSON.js
src/behaviors/columnProperties.js
src/behaviors/subgrids.js
src/cellEditors/CellEditor.js
src/cellRenderers/Button.js
src/dataModels/FilterSubgrid.js
src/dataModels/HeaderSubgrid.js
src/dataModels/InfoSubgrid.js
src/defaults.js
src/lib/Canvas.js
src/lib/cellEventFactory.js
src/lib/events.js
src/lib/polyfills.js
src/renderer/index.js

See Jira [GRID-441](https://appoji.jira.com/browse/GRID-441) for details.

GRID-441: Filter box shows NaN on commit

---

demo/js/aggregations-view.js
demo/js/computed-column.js
demo/js/demo.js
demo/js/group-view.js
demo/js/tree-view-separate-drill-down.js
demo/js/tree-view.js
demo/simple-column-sorting-pipeline.html
demo/sorting-and-filtering-pipeline.html
demo/stable-multi-column-sorting-pipeline.html

Sorting And Filtering Demo

---

src/lib/events.js
src/renderer/index.js

See [GRID-440](https://appoji.jira.com/browse/GRID-440)
@joneit

No events on blank space

---

demo/js/demo.js
src/Hypergrid.js
src/behaviors/Behavior.js
src/behaviors/Column.js
src/behaviors/cellProperties.js
src/behaviors/columnProperties.js
src/behaviors/subgrids.js
src/cellEditors/CellEditor.js
src/cellEditors/Textfield.js
src/cellRenderers/SimpleCell.js
src/dataModels/DataModel.js
src/defaults.js
src/features/CellEditing.js
src/features/CellSelection.js
src/features/Feature.js
src/lib/Canvas.js
src/lib/WritablePoint.js
src/lib/cellEventFactory.js
src/lib/events.js
src/lib/selection.js
src/renderer/index.js

There is no ticket associated with this PR.
Fixed vertical scroll max calculation (was not displaying final rows).
This in turn fixed `selectFinalCell` and `selectToFinalCell` which failed because final row was not displayable.
Also refined calculation of column with for handle column which was too narrow to accommodate row numbers when bolded (row selected) and was showing elipsis.

Select cell functions

---

.gitignore
.gitmodules
demo/js/demo.js
demo/row-props.html
src/Hypergrid.js
src/behaviors/Behavior.js
src/behaviors/Column.js
src/behaviors/JSON.js
src/behaviors/cellProperties.js
src/behaviors/subgrids.js
src/cellEditors/CellEditor.js
src/cellRenderers/SimpleCell.js
src/defaults.js
src/lib/Canvas.js
src/lib/cellEventFactory.js
src/lib/selection.js
src/renderer/by-cells.js
src/renderer/index.js

V1.2.10 mop up

---

README.md

Updated text for Development Roadmap section

Updated Roadmap section

---

demo/js/demo.js
demo/row-props.html
src/Hypergrid.js
src/behaviors/Behavior.js
src/defaults.js
src/features/CellClick.js
src/lib/cellEventFactory.js
src/renderer/index.js

See Jira [GRID-452](https://appoji.jira.com/browse/GRID-452) for details.

GRID-452: Links

---

demo/row-props.html
src/Hypergrid.js
src/lib/Canvas.js
src/lib/events.js
src/renderer/index.js

Difference between `fin-tick` and `fin-grid-rendered` events is that the latter (existing event) is only triggered when repaint was called for while the former (new event) is triggered on every `requestAnimationFrame` event regardless.
Needed by row-props demo.

Added a fin-tick event

---

demo/js/demo.js
src/Hypergrid.js
src/defaults.js
src/lib/dynamicProperties.js
src/renderer/index.js

See the [Jira ticket](https://appoji.jira.com/browse/GRID-439) for details.

GRID-439: Setting renderer at initialization

---

add-ons/hyper-sorter/index.js
add-ons/hyper-sorter/mix-ins/dataModel.js
demo/js/demo.js
package.json
src/Hypergrid.js
src/behaviors/Behavior.js
src/dataModels/JSON.js

See the [Jira ticket](https://appoji.jira.com/browse/GRID-460) for details including example usage.
This change requires:
```bash
npm update fin-hypergrid-data-source-base hyper-analytics
```

GRID-460: Access to drill-down and sort-direction glyphs

---

src/defaults.js
src/renderer/by-columns-and-rows.js
src/renderer/by-columns.js
src/renderer/by-rows.js
src/renderer/index.js

See Jira [GRID-462](https://appoji.jira.com/browse/GRID-462) for details.

GRID-462: Grid borders

---

.npmignore
add-ons/hyper-filter/js/ColumnSchemaFactory.js
add-ons/hyper-filter/mix-ins/behavior.js
add-ons/hyper-filter/mix-ins/grid.js
add-ons/hyper-sorter/mix-ins/behavior.js
add-ons/hyper-sorter/mix-ins/grid.js
gulpfile.js
index.js
package.json
src/index.js
src/lib/DataSourceOrigin.js

See 	4d65e09 extended comment for details.

Misc (see extended comment)

---

demo/aggregations-view.html
demo/computed-column.html
demo/group-view.html
demo/js/aggregations-view.js
demo/js/computed-column.js
demo/js/group-view.js
demo/js/tree-view-separate-drill-down.js
demo/js/tree-view.js
demo/simple-column-sorting-pipeline.html
demo/sorting-and-filtering-pipeline.html
demo/stable-multi-column-sorting-pipeline.html
demo/tree-view-separate-drill-down.html
demo/tree-view.html
src/behaviors/Behavior.js

…api. setPipeline must now be called before setting any controllers

GRID-467 Treeview and other demos fixed

---

demo/js/demo.js
src/behaviors/Behavior.js
src/lib/events.js

@joneit The wiki for this and all other events will be based on the GRID-400 pr. This pr is a patch to unblock William. We can send him a snippet showing the *current* and *temporary* event shape so that he can build his feature
in the pink demo
```
window.vent = true // will reveal the context-menu event object
```

GRID-463: Fin-Context-Menu Event

---

test/image-test.js

Turned off image tests due to conflict in Travis CI env

---

src/Hypergrid.js
src/behaviors/Behavior.js
src/behaviors/JSON.js
src/dataModels/JSON.js
src/lib/selection.js

See Jira [GRID-480](https://appoji.jira.com/browse/GRID-480) for details.

GRID-480: Row matrix needs includeHiddenColumns param

---

demo/js/demo.js
src/Hypergrid.js
src/defaults.js
src/lib/SelectionModel.js
src/lib/selection.js

See Jira [GRID-207](https://appoji.jira.com/browse/GRID-207) for details.
This also fixes error in demo dashboard introduced by earlier PR that's throwing a console error.

GRID-207: Single row selection mode

---

add-ons/dialog-ui/index.js
add-ons/hyper-sorter/index.js
demo/js/demo.js
src/lib/events.js

GRID-484: Hypergrid reset regression - listeners

---

src/cellEditors/ComboBox.js

Grid-456: Filter DropDown Scroll Issue

---

src/behaviors/columnProperties.js
src/defaults.js
src/lib/cellEventFactory.js
src/renderer/bundle-columns.js
src/renderer/bundle-rows.js
src/renderer/index.js

This additional PR for this ticket removes remnants of InfoGrid that I overlooked in the first PR.

GRID-485: Better no data message

---

demo/simple-column-sorting-pipeline.html

Simple Sorting Demo fixed using current Pipeline layer abstraction

Grid 201: Sorting

---

src/behaviors/Behavior.js
src/behaviors/columnProperties.js
src/defaults.js
src/renderer/index.js

Fixed misc problems that came out of the woodwork as I was writing the wiki.
See extended commit comment.

GRID-448: Computed columns, Part 2 (clean-up)

---

add-ons/hyper-filter/js/FilterSubgrid.js

Easy one. :P
See Jira [GIRD-469](https://appoji.jira.com/browse/GRID-469) for explanation.

GRID-469: 'fin-filter-applied' event not firing

---

src/lib/Canvas.js
src/lib/cellEventFactory.js

GRID-465: Hide hover effects when mouse leaves canvas element

---

add-ons/dialog-ui/dialogs/ManageFilters.js

@joneit 
Grid events were silenced when ManagedFilters Closed

GRID-493: Manage Filters Bug

---

src/features/ColumnMoving.js
src/features/ColumnResizing.js
src/lib/Canvas.js
src/lib/events.js
src/renderer/index.js

@joneit I intend to push an alpha tonight that won't be a 1.3.0 master target

GRID-455-459-475-470: Resize last col & Drag Cell Selectionm & Dragging Last Column

---

src/dataModels/JSON.js
src/lib/deprecated.js
src/lib/selection.js

GRID-495: Row selections after filter cell edit

---

package.json
src/behaviors/columnProperties.js
src/dataModels/JSON.js
src/lib/cellEventFactory.js

@joneit We can go over these tomorrow if you like

Couple of minor bugs in group and aggregations view

---

add-ons/group-view.js

@joneit This only affects group-view presentation

ISSUE#533: Empty Rows when Scrolling

---

src/features/Filters.js
src/lib/selection.js

@joneit See https://github.com/openfin/fin-hypergrid/issues/521

ISSUE#521: SelectViewPortCell 

---

add-ons/group-view.js
demo/js/demo.js
demo/js/group-view.js
package.json

ISSUE#560 - Group View Clears Column Formatting

---

demo/aggregations-view.html
demo/group-view.html
demo/simple-column-sorting-pipeline.html
demo/sorting-and-filtering-pipeline.html
demo/stable-multi-column-sorting-pipeline.html
demo/tree-column.html
demo/tree-view-separate-drill-down.html
demo/tree-view.html

Updated Demos

---

src/Hypergrid.js
src/behaviors/JSON.js
src/dataModels/JSON.js
src/renderer/index.js

More Cleanup

---

.gitignore
demo/js/demo/addDynamicProps.js
demo/js/demo/celleditors.js
demo/js/demo/cellrenderers.js
demo/js/demo/dashboard.js
demo/js/demo/events.js
demo/js/demo/formatters.js
demo/js/demo/index.js
demo/js/demo/setState.js
gulpfile.js
src/Hypergrid.js
src/behaviors/Behavior.js
src/behaviors/JSON.js
src/behaviors/columnEnumDecorators.js
src/lib/dynamicProperties.js
src/lib/index.js

See issue https://github.com/openfin/fin-hypergrid/issues/309 for details.
Task list:

ISSUE-309: Grid state

---

src/Hypergrid.js
src/dataModels/JSON.js
src/defaults.js
src/lib/dynamicProperties.js

Also, see the just-published wiki, [_Themes_](https://github.com/openfin/fin-hypergrid/wiki/Themes).

GRID-478: Refine theme support

---

src/Hypergrid.js

Fixed Grid reset

---

OVERVIEW.md

fix(#520) changes to OVERVIEW

---

.eslintrc
package.json
src/index.js

Hi guys @Dwaynekj @dcchuck This is a straight-forward PR to update eslint.
btw, I notice we now have squash merge set. Was this intentional? I would be happy to add my 2¢ to this decision.

Migrate eslint from v1 to v4

---

src/renderer/index.js

apply row props before cell props

---

demo/row-props.html

Just a few tweaks to `demo/row-props.html`.
There may be more to come....
As this is my baby I'll just merge it when I'm ready.

Grid Renderer demo adjustments

---

src/lib/selection.js

Original code was missing the emission of event.

Fire row selection event when auto selecting rows

---

src/features/RowSelection.js

Quick fix in logic to check whether keys contains the Shift key. If Shift is the first element of the array indexOf returns 0.

SHIFT can be the first key in the list

---

demo/row-props.html
src/behaviors/Behavior.js
src/behaviors/cellProperties.js
src/behaviors/columnProperties.js
src/dataModels/HeaderSubgrid.js
src/dataModels/JSON.js
src/defaults.js
src/lib/cellEventFactory.js
src/lib/dynamicProperties.js
src/renderer/bundle-rows.js
src/renderer/index.js

See issue #647. ~This PR is tentative based on performance impact.~ _Code has now gone through several rounds of testing/tweaking for performance. Performance checks out; please proceed with review._

Implement true row props

---

CONTRIBUTING.md
README.md
TESTING.md
TRANSITION-NOTES.md
demo/row-props.html
package-lock.json
package.json
src/behaviors/Behavior.js
src/behaviors/columnProperties.js
src/dataModels/DataModel.js
src/dataModels/HeaderSubgrid.js
src/dataModels/JSON.js
src/defaults.js
src/lib/dynamicProperties.js
src/renderer/bundle-rows.js
src/renderer/by-rows.js
src/renderer/index.js
version-history.md

Prepare release candidate 2.1.0

---

README.md
demo/index.html
demo/js/demo/index.js
demo/js/demo/setState.js
demo/multiple-grids.html
demo/row-props.html
package-lock.json
package.json
src/Base.js
src/Hypergrid.js
src/behaviors/Column.js
src/behaviors/columnProperties.js
src/defaults.js
src/features/Feature.js
src/lib/cellEventFactory.js
src/lib/dynamicProperties.js
src/lib/toFunction.js
src/themes.js

Back-porting more fixes from v3 branch...

Another v2 update (2.1.4)

---

src/behaviors/Behavior.js

Back-ported another 3.0 fix.
I want to leave v2 stable but this is getting tiresome.

fixed behavior.get/setValue

---

demo/js/demo/celleditors.js

To quash linter complaint. (Unfortunately linter wasn't running during demo development.)

hot fix to demo file

---

README.md
demo/index.html
demo/multiple-grids.html
demo/row-props.html
package-lock.json
package.json

This patch bumps the version numbers to match the tagged release. (It's always something.)

bump version number to 2.1.13

---

images/index.js
package.json
src/Hypergrid/events.js

Also resolve linter complaints.

Bump version number to v3.2.0

---

src/Hypergrid/index.js
src/behaviors/Column.js
src/features/TouchScrolling.js

texodus@1a12f7c
texodus@3cc996d

adjustments from texodus
